# Generated by Django 3.1.7 on 2021-05-06 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginapp', '0004_auto_20210430_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_gross_salary', models.FloatField()),
                ('tax_slab_percentage', models.FloatField()),
                ('taxable_income', models.FloatField()),
                ('net_payable_tax', models.FloatField()),
                ('auth', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
