# Generated by Django 3.1.7 on 2021-05-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='annual_gross_salary',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='auth',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='net_payable_tax',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='tax_slab_percentage',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='taxable_income',
        ),
        migrations.AddField(
            model_name='tax',
            name='Allowance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='Bonus',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='Citizen_Investment_Trust',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='Employee_Provident_Fund',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='Insurance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='Monthly_Salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='No_of_months',
            field=models.IntegerField(null=True),
        ),
    ]
