# Generated by Django 3.1.7 on 2021-05-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0006_auto_20210512_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='Allowance',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='Bonus',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='Citizen_Investment_Trust',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='Employee_Provident_Fund',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='Insurance',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='Monthly_Salary',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='No_of_months',
        ),
        migrations.AddField(
            model_name='tax',
            name='CIT',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='allowance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='bonus',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='emp_provident',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='insurance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='monthly_salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='no_months',
            field=models.IntegerField(null=True),
        ),
    ]
