# Generated by Django 3.1.7 on 2021-05-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0007_auto_20210512_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxable_income', models.IntegerField(null=True)),
                ('annual_gross_salary', models.IntegerField(null=True)),
                ('tax_slab_percentages', models.IntegerField(null=True)),
            ],
        ),
    ]
