# Generated by Django 3.1.7 on 2021-05-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0008_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='net_payable_tax',
            field=models.IntegerField(null=True),
        ),
    ]
