# Generated by Django 3.2 on 2021-05-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0009_history_net_payable_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='CIT',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='allowance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='bonus',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='emp_provident',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='insurance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='monthly_salary',
            field=models.FloatField(null=True),
        ),
    ]
