# Generated by Django 3.2 on 2021-05-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0011_taxone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='tax_slab_percentages',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
