# Generated by Django 3.1.7 on 2021-05-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0012_alter_history_tax_slab_percentages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='auth',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(default='body', max_length=1000),
        ),
        migrations.AlterField(
            model_name='taxone',
            name='tax_slab_percentage',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
